name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: psf/black@22.3.0
        with:
          options: "--line-length=99"
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: isort/isort-action@master
        with:
            configuration: "-l 99 --use-parentheses"
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
